version: '3.8'

services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - redis
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - backend

  restaurant-service:
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - backend

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - backend

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - backend

networks:
  backend:
