server:
  port: 8083  # Change port if needed

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/quickbite_orders
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
