server:
  port: 8082

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://postgres-db:5432/quickbite_restaurants
    username: postgres
    password: tiger

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
